#include "Stdafx.h"
#include "Text/StandardColor.h"

Text::CString Text::StandardColorGetName(StandardColor c)
{
	switch (c)
	{
	case StandardColor::Black:
		return CSTR("Black");
	case StandardColor::DarkBlue:
		return CSTR("DarkBlue");
	case StandardColor::ConsoleDarkGreen:
		return CSTR("ConsoleDarkGreen");
	case StandardColor::DarkCyan:
		return CSTR("DarkCyan");
	case StandardColor::DarkRed:
		return CSTR("DarkRed");
	case StandardColor::DarkMagenta:
		return CSTR("DarkMagenta");
	case StandardColor::DarkYellow:
		return CSTR("DarkYellow");
	case StandardColor::Gray:
		return CSTR("Gray");
	case StandardColor::DarkGray:
		return CSTR("DarkGray");
	case StandardColor::Blue:
		return CSTR("Blue");
	case StandardColor::Lime:
		return CSTR("Lime");
	case StandardColor::Cyan:
		return CSTR("Cyan");
	case StandardColor::Red:
		return CSTR("Red");
	case StandardColor::Magenta:
		return CSTR("Magenta");
	case StandardColor::Yellow:
		return CSTR("Yellow");
	case StandardColor::White:
		return CSTR("White");
	case StandardColor::IndianRed:
		return CSTR("IndianRed");
	case StandardColor::LightCoral:
		return CSTR("LightCoral");
	case StandardColor::Salmon:
		return CSTR("Salmon");
	case StandardColor::DarkSalmon:
		return CSTR("DarkSalmon");
	case StandardColor::LightSalmon:
		return CSTR("LightSalmon");
	case StandardColor::Crimson:
		return CSTR("Crimson");
	case StandardColor::FireBrick:
		return CSTR("FireBrick");
	case StandardColor::Pink:
		return CSTR("Pink");
	case StandardColor::LightPink:
		return CSTR("LightPink");
	case StandardColor::HotPink:
		return CSTR("HotPink");
	case StandardColor::DeepPink:
		return CSTR("DeepPink");
	case StandardColor::MediumVioletRed:
		return CSTR("MediumVioletRed");
	case StandardColor::PaleVioletRed:
		return CSTR("PaleVioletRed");
	case StandardColor::Coral:
		return CSTR("Coral");
	case StandardColor::Tomato:
		return CSTR("Tomato");
	case StandardColor::OrangeRed:
		return CSTR("OrangeRed");
	case StandardColor::DarkOrange:
		return CSTR("DarkOrange");
	case StandardColor::Orange:
		return CSTR("Orange");
	case StandardColor::Gold:
		return CSTR("Gold");
	case StandardColor::LightYellow:
		return CSTR("LightYellow");
	case StandardColor::LemonChiffon:
		return CSTR("LemonChiffon");
	case StandardColor::LightGoldenrodYellow:
		return CSTR("LightGoldenrodYellow");
	case StandardColor::PapayaWhip:
		return CSTR("PapayaWhip");
	case StandardColor::Moccasin:
		return CSTR("Moccasin");
	case StandardColor::PeachPuff:
		return CSTR("PeachPuff");
	case StandardColor::PaleGoldenrod:
		return CSTR("PaleGoldenrod");
	case StandardColor::Khaki:
		return CSTR("Khaki");
	case StandardColor::DarkKhaki:
		return CSTR("DarkKhaki");
	case StandardColor::Lavender:
		return CSTR("Lavender");
	case StandardColor::Thistle:
		return CSTR("Thistle");
	case StandardColor::Plum:
		return CSTR("Plum");
	case StandardColor::Violet:
		return CSTR("Violet");
	case StandardColor::Orchid:
		return CSTR("Orchid");
	case StandardColor::Fuchsia:
		return CSTR("Fuchsia");
	case StandardColor::MediumOrchid:
		return CSTR("MediumOrchid");
	case StandardColor::MediumPurple:
		return CSTR("MediumPurple");
	case StandardColor::RebeccaPurple:
		return CSTR("RebeccaPurple");
	case StandardColor::BlueViolet:
		return CSTR("BlueViolet");
	case StandardColor::DarkViolet:
		return CSTR("DarkViolet");
	case StandardColor::DarkOrchid:
		return CSTR("DarkOrchid");
	case StandardColor::Purple:
		return CSTR("Purple");
	case StandardColor::Indigo:
		return CSTR("Indigo");
	case StandardColor::SlateBlue:
		return CSTR("SlateBlue");
	case StandardColor::DarkSlateBlue:
		return CSTR("DarkSlateBlue");
	case StandardColor::MediumSlateBlue:
		return CSTR("MediumSlateBlue");
	case StandardColor::GreenYellow:
		return CSTR("GreenYellow");
	case StandardColor::Chartreuse:
		return CSTR("Chartreuse");
	case StandardColor::LawnGreen:
		return CSTR("LawnGreen");
	case StandardColor::LimeGreen:
		return CSTR("LimeGreen");
	case StandardColor::PaleGreen:
		return CSTR("PaleGreen");
	case StandardColor::LightGreen:
		return CSTR("LightGreen");
	case StandardColor::MediumSpringGreen:
		return CSTR("MediumSpringGreen");
	case StandardColor::SpringGreen:
		return CSTR("SpringGreen");
	case StandardColor::MediumSeaGreen:
		return CSTR("MediumSeaGreen");
	case StandardColor::SeaGreen:
		return CSTR("SeaGreen");
	case StandardColor::ForestGreen:
		return CSTR("ForestGreen");
	case StandardColor::Green:
		return CSTR("Green");
	case StandardColor::DarkGreen:
		return CSTR("DarkGreen");
	case StandardColor::YellowGreen:
		return CSTR("YellowGreen");
	case StandardColor::OliveDrab:
		return CSTR("OliveDrab");
	case StandardColor::Olive:
		return CSTR("Olive");
	case StandardColor::DarkOliveGreen:
		return CSTR("DarkOliveGreen");
	case StandardColor::MediumAquamarine:
		return CSTR("MediumAquamarine");
	case StandardColor::DarkSeaGreen:
		return CSTR("DarkSeaGreen");
	case StandardColor::LightSeaGreen:
		return CSTR("LightSeaGreen");
	case StandardColor::Teal:
		return CSTR("Teal");
	case StandardColor::Aqua:
		return CSTR("Aqua");
	case StandardColor::LightCyan:
		return CSTR("LightCyan");
	case StandardColor::PaleTurquoise:
		return CSTR("PaleTurquoise");
	case StandardColor::Aquamarine:
		return CSTR("Aquamarine");
	case StandardColor::Turquoise:
		return CSTR("Turquoise");
	case StandardColor::MediumTurquoise:
		return CSTR("MediumTurquoise");
	case StandardColor::DarkTurquoise:
		return CSTR("DarkTurquoise");
	case StandardColor::CadetBlue:
		return CSTR("CadetBlue");
	case StandardColor::SteelBlue:
		return CSTR("SteelBlue");
	case StandardColor::LightSteelBlue:
		return CSTR("LightSteelBlue");
	case StandardColor::PowderBlue:
		return CSTR("PowderBlue");
	case StandardColor::LightBlue:
		return CSTR("LightBlue");
	case StandardColor::SkyBlue:
		return CSTR("SkyBlue");
	case StandardColor::LightSkyBlue:
		return CSTR("LightSkyBlue");
	case StandardColor::DeepSkyBlue:
		return CSTR("DeepSkyBlue");
	case StandardColor::DodgerBlue:
		return CSTR("DodgerBlue");
	case StandardColor::CornflowerBlue:
		return CSTR("CornflowerBlue");
	case StandardColor::RoyalBlue:
		return CSTR("RoyalBlue");
	case StandardColor::MediumBlue:
		return CSTR("MediumBlue");
	case StandardColor::Navy:
		return CSTR("Navy");
	case StandardColor::MidnightBlue:
		return CSTR("MidnightBlue");
	case StandardColor::Cornsilk:
		return CSTR("Cornsilk");
	case StandardColor::BlanchedAlmond:
		return CSTR("BlanchedAlmond");
	case StandardColor::Bisque:
		return CSTR("Bisque");
	case StandardColor::NavajoWhite:
		return CSTR("NavajoWhite");
	case StandardColor::Wheat:
		return CSTR("Wheat");
	case StandardColor::BurlyWood:
		return CSTR("BurlyWood");
	case StandardColor::Tan:
		return CSTR("Tan");
	case StandardColor::RosyBrown:
		return CSTR("RosyBrown");
	case StandardColor::SandyBrown:
		return CSTR("SandyBrown");
	case StandardColor::Goldenrod:
		return CSTR("Goldenrod");
	case StandardColor::DarkGoldenrod:
		return CSTR("DarkGoldenrod");
	case StandardColor::Peru:
		return CSTR("Peru");
	case StandardColor::Chocolate:
		return CSTR("Chocolate");
	case StandardColor::SaddleBrown:
		return CSTR("SaddleBrown");
	case StandardColor::Sienna:
		return CSTR("Sienna");
	case StandardColor::Brown:
		return CSTR("Brown");
	case StandardColor::Maroon:
		return CSTR("Maroon");
	case StandardColor::Snow:
		return CSTR("Snow");
	case StandardColor::HoneyDew:
		return CSTR("HoneyDew");
	case StandardColor::MintCream:
		return CSTR("MintCream");
	case StandardColor::Azure:
		return CSTR("Azure");
	case StandardColor::AliceBlue:
		return CSTR("AliceBlue");
	case StandardColor::GhostWhite:
		return CSTR("GhostWhite");
	case StandardColor::WhiteSmoke:
		return CSTR("WhiteSmoke");
	case StandardColor::SeaShell:
		return CSTR("SeaShell");
	case StandardColor::Beige:
		return CSTR("Beige");
	case StandardColor::OldLace:
		return CSTR("OldLace");
	case StandardColor::FloralWhite:
		return CSTR("FloralWhite");
	case StandardColor::Ivory:
		return CSTR("Ivory");
	case StandardColor::AntiqueWhite:
		return CSTR("AntiqueWhite");
	case StandardColor::Linen:
		return CSTR("Linen");
	case StandardColor::LavenderBlush:
		return CSTR("LavenderBlush");
	case StandardColor::MistyRose:
		return CSTR("MistyRose");
	case StandardColor::Gainsboro:
		return CSTR("Gainsboro");
	case StandardColor::LightGray:
		return CSTR("LightGray");
	case StandardColor::Silver:
		return CSTR("Silver");
	case StandardColor::DimGray:
		return CSTR("DimGray");
	case StandardColor::LightSlateGray:
		return CSTR("LightSlateGray");
	case StandardColor::SlateGray:
		return CSTR("SlateGray");
	case StandardColor::DarkSlateGray:
		return CSTR("DarkSlateGray");
	default:
		return CSTR("Unknwon");
	}
}

UInt32 Text::StandardColorGetARGB32(StandardColor c)
{
	switch (c)
	{
	case StandardColor::Black:
		return 0xFF000000;
	case StandardColor::DarkBlue:
		return 0xFF00008B;
	case StandardColor::ConsoleDarkGreen:
		return 0xFF008B00;
	case StandardColor::DarkCyan:
		return 0xFF008B8B;
	case StandardColor::DarkRed:
		return 0xFF8B0000;
	case StandardColor::DarkMagenta:
		return 0xFF8B008B;
	case StandardColor::DarkYellow:
		return 0xFF8B8B00;
	case StandardColor::Gray:
		return 0xFF808080;
	case StandardColor::DarkGray:
		return 0xFFA9A9A9;
	case StandardColor::Blue:
		return 0xFF0000FF;
	case StandardColor::Lime:
		return 0xFF00FF00;
	case StandardColor::Cyan:
		return 0xFF00FFFF;
	case StandardColor::Red:
		return 0xFFFF0000;
	case StandardColor::Magenta:
		return 0xFFFF00FF;
	case StandardColor::Yellow:
		return 0xFFFFFF00;
	case StandardColor::White:
		return 0xFFFFFFFF;
	case StandardColor::IndianRed:
		return 0xFFCD5C5C;
	case StandardColor::LightCoral:
		return 0xFFF08080;
	case StandardColor::Salmon:
		return 0xFFFA8072;
	case StandardColor::DarkSalmon:
		return 0xFFE9967A;
	case StandardColor::LightSalmon:
		return 0xFFFFA07A;
	case StandardColor::Crimson:
		return 0xFFDC143C;
	case StandardColor::FireBrick:
		return 0xFFB22222;
	case StandardColor::Pink:
		return 0xFFFFC0CB;
	case StandardColor::LightPink:
		return 0xFFFFB6C1;
	case StandardColor::HotPink:
		return 0xFFFF69B4;
	case StandardColor::DeepPink:
		return 0xFFFF1493;
	case StandardColor::MediumVioletRed:
		return 0xFFC71585;
	case StandardColor::PaleVioletRed:
		return 0xFFDB7093;
	case StandardColor::Coral:
		return 0xFFFF7F50;
	case StandardColor::Tomato:
		return 0xFFFF6347;
	case StandardColor::OrangeRed:
		return 0xFFFF4500;
	case StandardColor::DarkOrange:
		return 0xFFFF8C00;
	case StandardColor::Orange:
		return 0xFFFFA500;
	case StandardColor::Gold:
		return 0xFFFFD700;
	case StandardColor::LightYellow:
		return 0xFFFFFFE0;
	case StandardColor::LemonChiffon:
		return 0xFFFFFACD;
	case StandardColor::LightGoldenrodYellow:
		return 0xFFFAFAD2;
	case StandardColor::PapayaWhip:
		return 0xFFFFEFD5;
	case StandardColor::Moccasin:
		return 0xFFFFE4B5;
	case StandardColor::PeachPuff:
		return 0xFFFFDAB9;
	case StandardColor::PaleGoldenrod:
		return 0xFFEEE8AA;
	case StandardColor::Khaki:
		return 0xFFF0E68C;
	case StandardColor::DarkKhaki:
		return 0xFFBDB76B;
	case StandardColor::Lavender:
		return 0xFFE6E6FA;
	case StandardColor::Thistle:
		return 0xFFD8BFD8;
	case StandardColor::Plum:
		return 0xFFDDA0DD;
	case StandardColor::Violet:
		return 0xFFEE82EE;
	case StandardColor::Orchid:
		return 0xFFDA70D6;
	case StandardColor::Fuchsia:
		return 0xFFFF00FF;
	case StandardColor::MediumOrchid:
		return 0xFFBA55D3;
	case StandardColor::MediumPurple:
		return 0xFF9370DB;
	case StandardColor::RebeccaPurple:
		return 0xFF663399;
	case StandardColor::BlueViolet:
		return 0xFF8A2BE2;
	case StandardColor::DarkViolet:
		return 0xFF9400D3;
	case StandardColor::DarkOrchid:
		return 0xFF9932CC;
	case StandardColor::Purple:
		return 0xFF800080;
	case StandardColor::Indigo:
		return 0xFF4B0082;
	case StandardColor::SlateBlue:
		return 0xFF6A5ACD;
	case StandardColor::DarkSlateBlue:
		return 0xFF483D8B;
	case StandardColor::MediumSlateBlue:
		return 0xFF7B68EE;
	case StandardColor::GreenYellow:
		return 0xFFADFF2F;
	case StandardColor::Chartreuse:
		return 0xFF7FFF00;
	case StandardColor::LawnGreen:
		return 0xFF7CFC00;
	case StandardColor::LimeGreen:
		return 0xFF32CD32;
	case StandardColor::PaleGreen:
		return 0xFF98FB98;
	case StandardColor::LightGreen:
		return 0xFF90EE90;
	case StandardColor::MediumSpringGreen:
		return 0xFF00FA9A;
	case StandardColor::SpringGreen:
		return 0xFF00FF7F;
	case StandardColor::MediumSeaGreen:
		return 0xFF3CB371;
	case StandardColor::SeaGreen:
		return 0xFF2E8B57;
	case StandardColor::ForestGreen:
		return 0xFF228B22;
	case StandardColor::Green:
		return 0xFF008000;
	case StandardColor::DarkGreen:
		return 0xFF006400;
	case StandardColor::YellowGreen:
		return 0xFF9ACD32;
	case StandardColor::OliveDrab:
		return 0xFF6B8E23;
	case StandardColor::Olive:
		return 0xFF808000;
	case StandardColor::DarkOliveGreen:
		return 0xFF556B2F;
	case StandardColor::MediumAquamarine:
		return 0xFF66CDAA;
	case StandardColor::DarkSeaGreen:
		return 0xFF8FBC8B;
	case StandardColor::LightSeaGreen:
		return 0xFF20B2AA;
	case StandardColor::Teal:
		return 0xFF008B8B;
	case StandardColor::Aqua:
		return 0xFF008080;
	case StandardColor::LightCyan:
		return 0xFFE0FFFF;
	case StandardColor::PaleTurquoise:
		return 0xFFAFEEEE;
	case StandardColor::Aquamarine:
		return 0xFF7FFFD4;
	case StandardColor::Turquoise:
		return 0xFF40E0D0;
	case StandardColor::MediumTurquoise:
		return 0xFF48D1CC;
	case StandardColor::DarkTurquoise:
		return 0xFF00CED1;
	case StandardColor::CadetBlue:
		return 0xFF5F9EA0;
	case StandardColor::SteelBlue:
		return 0xFF4682B4;
	case StandardColor::LightSteelBlue:
		return 0xFFB0C4DE;
	case StandardColor::PowderBlue:
		return 0xFFB0E0E6;
	case StandardColor::LightBlue:
		return 0xFFADD8E6;
	case StandardColor::SkyBlue:
		return 0xFF87CEEB;
	case StandardColor::LightSkyBlue:
		return 0xFF87CEFA;
	case StandardColor::DeepSkyBlue:
		return 0xFF00BFFF;
	case StandardColor::DodgerBlue:
		return 0xFF1E90FF;
	case StandardColor::CornflowerBlue:
		return 0xFF6495ED;
	case StandardColor::RoyalBlue:
		return 0xFF4169E1;
	case StandardColor::MediumBlue:
		return 0xFF0000CD;
	case StandardColor::Navy:
		return 0xFF000080;
	case StandardColor::MidnightBlue:
		return 0xFF191970;
	case StandardColor::Cornsilk:
		return 0xFFFFF8DC;
	case StandardColor::BlanchedAlmond:
		return 0xFFFFEBCD;
	case StandardColor::Bisque:
		return 0xFFFFE4C4;
	case StandardColor::NavajoWhite:
		return 0xFFFFDEAD;
	case StandardColor::Wheat:
		return 0xFFF5DEB3;
	case StandardColor::BurlyWood:
		return 0xFFDEB887;
	case StandardColor::Tan:
		return 0xFFD2B48C;
	case StandardColor::RosyBrown:
		return 0xFFBC8F8F;
	case StandardColor::SandyBrown:
		return 0xFFF4A460;
	case StandardColor::Goldenrod:
		return 0xFFDAA520;
	case StandardColor::DarkGoldenrod:
		return 0xFFB8860B;
	case StandardColor::Peru:
		return 0xFFCD853F;
	case StandardColor::Chocolate:
		return 0xFFD2691E;
	case StandardColor::SaddleBrown:
		return 0xFF8B4513;
	case StandardColor::Sienna:
		return 0xFFA0522D;
	case StandardColor::Brown:
		return 0xFFA52A2A;
	case StandardColor::Maroon:
		return 0xFF800000;
	case StandardColor::Snow:
		return 0xFFFFFAFA;
	case StandardColor::HoneyDew:
		return 0xFFF0FFF0;
	case StandardColor::MintCream:
		return 0xFFF5FFFA;
	case StandardColor::Azure:
		return 0xFFF0FFFF;
	case StandardColor::AliceBlue:
		return 0xFFF0F8FF;
	case StandardColor::GhostWhite:
		return 0xFFF8F8FF;
	case StandardColor::WhiteSmoke:
		return 0xFFF5F5F5;
	case StandardColor::SeaShell:
		return 0xFFFFF5EE;
	case StandardColor::Beige:
		return 0xFFF5F5DC;
	case StandardColor::OldLace:
		return 0xFFFDF5E6;
	case StandardColor::FloralWhite:
		return 0xFFFFFAF0;
	case StandardColor::Ivory:
		return 0xFFFFFFF0;
	case StandardColor::AntiqueWhite:
		return 0xFFFAEBD7;
	case StandardColor::Linen:
		return 0xFFFAF0E6;
	case StandardColor::LavenderBlush:
		return 0xFFFFF0F5;
	case StandardColor::MistyRose:
		return 0xFFFFE4E1;
	case StandardColor::Gainsboro:
		return 0xFFDCDCDC;
	case StandardColor::LightGray:
		return 0xFFD3D3D3;
	case StandardColor::Silver:
		return 0xFFC0C0C0;
	case StandardColor::DimGray:
		return 0xFF696969;
	case StandardColor::LightSlateGray:
		return 0xFF778899;
	case StandardColor::SlateGray:
		return 0xFF708090;
	case StandardColor::DarkSlateGray:
		return 0xFF2F4F4F;
	default:
		return 0xFF000000;
	}
}
