#ifndef _SM_MAP_ESRI_ESRIFEATURESERVER
#define _SM_MAP_ESRI_ESRIFEATURESERVER
#include "Data/ArrayListDbl.h"
#include "IO/Stream.h"
#include "Map/DrawMapService.h"
#include "Math/CoordinateSystem.h"
#include "Net/JSONResponse.h"
#include "Net/SocketFactory.h"
#include "Net/SSLEngine.h"
#include "Text/JSON.h"
#include "Text/String.h"

namespace Map
{
	namespace ESRI
	{
		class ESRIFeatureServer
		{
		public:
			JSONRESP_BEGIN(SpatialReference)
			JSONRESP_DOUBLE("falseM",false,false)
			JSONRESP_DOUBLE("falseX",false,false)
			JSONRESP_DOUBLE("falseY",false,false)
			JSONRESP_DOUBLE("falseZ",false,false)
			JSONRESP_DOUBLE("latestWkid",false,false)
			JSONRESP_DOUBLE("mTolerance",false,false)
			JSONRESP_DOUBLE("mUnits",false,false)
			JSONRESP_DOUBLE("wkid",false,false)
			JSONRESP_DOUBLE("xyTolerance",false,false)
			JSONRESP_DOUBLE("xyUnits",false,false)
			JSONRESP_DOUBLE("zTolerance",false,false)
			JSONRESP_DOUBLE("zUnits",false,false)
			JSONRESP_SEC_GET(SpatialReference)
			JSONRESP_GETDOUBLE("falseM",GetFalseM,0.0)
			JSONRESP_GETDOUBLE("falseX",GetFalseX,0.0)
			JSONRESP_GETDOUBLE("falseY",GetFalseY,0.0)
			JSONRESP_GETDOUBLE("falseZ",GetFalseZ,0.0)
			JSONRESP_GETDOUBLE("latestWkid",GetLatestWkid,0.0)
			JSONRESP_GETDOUBLE("mTolerance",GetMTolerance,0.0)
			JSONRESP_GETDOUBLE("mUnits",GetMUnits,0.0)
			JSONRESP_GETDOUBLE("wkid",GetWkid,0.0)
			JSONRESP_GETDOUBLE("xyTolerance",GetXyTolerance,0.0)
			JSONRESP_GETDOUBLE("xyUnits",GetXyUnits,0.0)
			JSONRESP_GETDOUBLE("zTolerance",GetZTolerance,0.0)
			JSONRESP_GETDOUBLE("zUnits",GetZUnits,0.0)
			JSONRESP_END

			JSONRESP_BEGIN(Extent)
			JSONRESP_OBJ("spatialReference",false,false,SpatialReference)
			JSONRESP_DOUBLE("xmax",false,false)
			JSONRESP_DOUBLE("xmin",false,false)
			JSONRESP_DOUBLE("ymax",false,false)
			JSONRESP_DOUBLE("ymin",false,false)
			JSONRESP_SEC_GET(Extent)
			JSONRESP_GETOBJ("spatialReference",GetSpatialReference,SpatialReference)
			JSONRESP_GETDOUBLE("xmax",GetXmax,0.0)
			JSONRESP_GETDOUBLE("xmin",GetXmin,0.0)
			JSONRESP_GETDOUBLE("ymax",GetYmax,0.0)
			JSONRESP_GETDOUBLE("ymin",GetYmin,0.0)
			JSONRESP_END

			JSONRESP_BEGIN(TimeReference)
			JSONRESP_BOOL("respectsDaylightSaving",false,false)
			JSONRESP_STR("timeZone",false,false)
			JSONRESP_SEC_GET(TimeReference)
			JSONRESP_GETBOOL("respectsDaylightSaving",IsRespectsDaylightSaving)
			JSONRESP_GETSTR("timeZone",GetTimeZone)
			JSONRESP_END

			JSONRESP_BEGIN(AdvancedEditingCapabilities)
			JSONRESP_BOOL("supportsAsyncApplyEdits",false,false)
			JSONRESP_ARRAY_STR("supportedSqlFormatsInCalculate",false,false)
			JSONRESP_SEC_GET(AdvancedEditingCapabilities)
			JSONRESP_GETBOOL("supportsAsyncApplyEdits",IsSupportsAsyncApplyEdits)
			JSONRESP_GETARRAY_STR("supportedSqlFormatsInCalculate",IsSupportedSqlFormatsInCalculate)
			JSONRESP_END

			JSONRESP_BEGIN(AdvancedQueryCapabilities)
			JSONRESP_BOOL("supportsCountDistinct",false,false)
			JSONRESP_BOOL("supportsDistinct",false,false)
			JSONRESP_BOOL("supportsHavingClause",false,false)
			JSONRESP_BOOL("supportsLod",false,false)
			JSONRESP_BOOL("supportsOrderBy",false,false)
			JSONRESP_BOOL("supportsPagination",false,false)
			JSONRESP_BOOL("supportsPercentileStatistics",false,false)
			JSONRESP_BOOL("supportsQueryAnalytic",false,false)
			JSONRESP_BOOL("supportsQueryWithDatumTransformation",false,false)
			JSONRESP_BOOL("supportsQueryWithDistance",false,false)
			JSONRESP_BOOL("supportsQueryWithLodSR",false,false)
			JSONRESP_BOOL("supportsQueryWithResultType",false,false)
			JSONRESP_BOOL("supportsReturningGeometryCentroid",false,false)
			JSONRESP_BOOL("supportsReturningQueryExtent",false,false)
			JSONRESP_BOOL("supportsSqlExpression",false,false)
			JSONRESP_BOOL("supportsStatistics",false,false)
			JSONRESP_BOOL("supportsTrueCurve",false,false)
			JSONRESP_SEC_GET(AdvancedQueryCapabilities)
			JSONRESP_GETBOOL("supportsCountDistinct",IsSupportsCountDistinct)
			JSONRESP_GETBOOL("supportsDistinct",IsSupportsDistinct)
			JSONRESP_GETBOOL("supportsHavingClause",IsSupportsHavingClause)
			JSONRESP_GETBOOL("supportsLod",IsSupportsLod)
			JSONRESP_GETBOOL("supportsOrderBy",IsSupportsOrderBy)
			JSONRESP_GETBOOL("supportsPagination",IsSupportsPagination)
			JSONRESP_GETBOOL("supportsPercentileStatistics",IsSupportsPercentileStatistics)
			JSONRESP_GETBOOL("supportsQueryAnalytic",IsSupportsQueryAnalytic)
			JSONRESP_GETBOOL("supportsQueryWithDatumTransformation",IsSupportsQueryWithDatumTransformation)
			JSONRESP_GETBOOL("supportsQueryWithDistance",IsSupportsQueryWithDistance)
			JSONRESP_GETBOOL("supportsQueryWithLodSR",IsSupportsQueryWithLodSR)
			JSONRESP_GETBOOL("supportsQueryWithResultType",IsSupportsQueryWithResultType)
			JSONRESP_GETBOOL("supportsReturningGeometryCentroid",IsSupportsReturningGeometryCentroid)
			JSONRESP_GETBOOL("supportsReturningQueryExtent",IsSupportsReturningQueryExtent)
			JSONRESP_GETBOOL("supportsSqlExpression",IsSupportsSqlExpression)
			JSONRESP_GETBOOL("supportsStatistics",IsSupportsStatistics)
			JSONRESP_GETBOOL("supportsTrueCurve",IsSupportsTrueCurve)
			JSONRESP_END

			JSONRESP_BEGIN(ArchivingInfo)
			JSONRESP_DOUBLE("startArchivingMoment",false,false)
			JSONRESP_BOOL("supportsQueryWithHistoricMoment",false,false)
			JSONRESP_SEC_GET(ArchivingInfo)
			JSONRESP_GETDOUBLE("startArchivingMoment",GetStartArchivingMoment,0.0)
			JSONRESP_GETBOOL("supportsQueryWithHistoricMoment",IsSupportsQueryWithHistoricMoment)
			JSONRESP_END
		
			JSONRESP_BEGIN(PrototypeAttribute)
			JSONRESP_ALLOW_ALL
			JSONRESP_SEC_GET(PrototypeAttribute)
			JSONRESP_END

			JSONRESP_BEGIN(Prototype)
			JSONRESP_OBJ("attributes",false,false,PrototypeAttribute)
			JSONRESP_SEC_GET(Prototype)
			JSONRESP_GETOBJ("attributes",GetAttributes,PrototypeAttribute)
			JSONRESP_END

			JSONRESP_BEGIN(Template)
			JSONRESP_STR("description",false,false)
			JSONRESP_STR("drawingTool",false,false)
			JSONRESP_STR("name",false,false)
			JSONRESP_OBJ("prototype",false,false,Prototype)
			JSONRESP_SEC_GET(Template)
			JSONRESP_GETSTR("description",GetDescription)
			JSONRESP_GETSTR("drawingTool",GetDrawingTool)
			JSONRESP_GETSTR("name",GetName)
			JSONRESP_GETOBJ("prototype",GetPrototype,Prototype)
			JSONRESP_END

			JSONRESP_BEGIN(Domain)
			JSONRESP_STR("description",false,true)
			JSONRESP_SEC_GET(Domain)
			JSONRESP_GETSTROPT("description",GetDescription)
			JSONRESP_END

			JSONRESP_BEGIN(TypeInfo)
			JSONRESP_ARRAY_OBJ("domains",false,false,Domain)
			JSONRESP_STR("id",false,false)
			JSONRESP_STR("name",false,false)
			JSONRESP_ARRAY_OBJ("templates",false,false,Template)
			JSONRESP_SEC_GET(TypeInfo)
			JSONRESP_GETARRAY_OBJ("domains",GetDomains,Domain)
			JSONRESP_GETSTR("id",GetId)
			JSONRESP_GETSTR("name",GetName)
			JSONRESP_GETARRAY_OBJ("templates",GetTemplates,Template)
			JSONRESP_END

			JSONRESP_BEGIN(Relationship)
			JSONRESP_DOUBLE("id",false,false)
			JSONRESP_STR("name",false,false)
			JSONRESP_DOUBLE("relatedTableId",false,false)
			JSONRESP_STR("cardinality",false,false)
			JSONRESP_STR("role",false,false)
			JSONRESP_STR("keyField",false,false)
			JSONRESP_BOOL("composite",false,false)
			JSONRESP_STR("catalogID",false,false)
			JSONRESP_DOUBLE("relationshipTableId",true,false)
			JSONRESP_STR("keyFieldInRelationshipTable",true,false)
			JSONRESP_SEC_GET(Relationship)
			JSONRESP_GETDOUBLE("id",GetId, 0.0)
			JSONRESP_GETSTR("name",GetName)
			JSONRESP_GETDOUBLE("relatedTableId",GetRelatedTableId, 0.0)
			JSONRESP_GETSTR("cardinality",GetCardinality)
			JSONRESP_GETSTR("role",GetRole)
			JSONRESP_GETSTR("keyField",GetKeyField)
			JSONRESP_GETBOOL("composite",IsComposite)
			JSONRESP_GETSTR("catalogID",GetCatalogID)
			JSONRESP_GETDOUBLE("relationshipTableId",GetRelationshipTableId, 0.0)
			JSONRESP_GETSTR("keyFieldInRelationshipTable",GetKeyFieldInRelationshipTable)
			JSONRESP_END
		
			JSONRESP_BEGIN(SymbolOutline)
			JSONRESP_ARRAY_DOUBLE("color",false,false)
			JSONRESP_DOUBLE("width",false,false)
			JSONRESP_SEC_GET(SymbolOutline)
			JSONRESP_GETARRAY_DOUBLE("color",IsColor)
			JSONRESP_GETDOUBLE("width",GetWidth,0.0)
			JSONRESP_END

			JSONRESP_BEGIN(RendererSymbol)
			JSONRESP_DOUBLE("angle",false,false)
			JSONRESP_ARRAY_DOUBLE("color",false,false)
			JSONRESP_OBJ("outline",false,false,SymbolOutline)
			JSONRESP_DOUBLE("size",false,false)
			JSONRESP_STR("style",false,false)
			JSONRESP_STR("type",false,false)
			JSONRESP_DOUBLE("xoffset",false,false)
			JSONRESP_DOUBLE("yoffset",false,false)
			JSONRESP_SEC_GET(RendererSymbol)
			JSONRESP_GETDOUBLE("angle",GetAngle,0.0)
			JSONRESP_GETARRAY_DOUBLE("color",IsColor)
			JSONRESP_GETOBJ("outline",GetOutline,SymbolOutline)
			JSONRESP_GETDOUBLE("size",GetSize,0.0)
			JSONRESP_GETSTR("style",GetStyle)
			JSONRESP_GETSTR("type",GetType)
			JSONRESP_GETDOUBLE("xoffset",GetXoffset,0.0)
			JSONRESP_GETDOUBLE("yoffset",GetYoffset,0.0)
			JSONRESP_END

			JSONRESP_BEGIN(Renderer)
			JSONRESP_OBJ("symbol",false,false,RendererSymbol)
			JSONRESP_STR("type",false,false)
			JSONRESP_SEC_GET(Renderer)
			JSONRESP_GETOBJ("symbol",GetSymbol,RendererSymbol)
			JSONRESP_GETSTR("type",GetType)
			JSONRESP_END

			JSONRESP_BEGIN(DrawingInfo)
			JSONRESP_STR("labelingInfo",false,true)
			JSONRESP_OBJ("renderer",false,false,Renderer)
			JSONRESP_BOOL("scaleSymbols",false,false)
			JSONRESP_DOUBLE("transparency",false,false)
			JSONRESP_SEC_GET(DrawingInfo)
			JSONRESP_GETSTROPT("labelingInfo",GetLabelingInfo)
			JSONRESP_GETOBJ("renderer",GetRenderer,Renderer)
			JSONRESP_GETBOOL("scaleSymbols",IsScaleSymbols)
			JSONRESP_GETDOUBLE("transparency",GetTransparency,0.0)
			JSONRESP_END

			JSONRESP_BEGIN(GeometryField)
			JSONRESP_STR("alias",false,false)
			JSONRESP_STR("defaultValue",false,true)
			JSONRESP_STR("domain",false,true)
			JSONRESP_BOOL("editable",false,false)
			JSONRESP_STR("modelName",false,false)
			JSONRESP_STR("name",false,false)
			JSONRESP_BOOL("nullable",false,false)
			JSONRESP_STR("type",false,false)
			JSONRESP_SEC_GET(GeometryField)
			JSONRESP_GETSTR("alias",GetAlias)
			JSONRESP_GETSTROPT("defaultValue",GetDefaultValue)
			JSONRESP_GETSTROPT("domain",GetDomain)
			JSONRESP_GETBOOL("editable",IsEditable)
			JSONRESP_GETSTR("modelName",GetModelName)
			JSONRESP_GETSTR("name",GetName)
			JSONRESP_GETBOOL("nullable",IsNullable)
			JSONRESP_GETSTR("type",GetType)
			JSONRESP_END

			JSONRESP_BEGIN(LayerIndex)
			JSONRESP_STR("description",false,false)
			JSONRESP_STR("fields",false,false)
			JSONRESP_BOOL("isAscending",false,false)
			JSONRESP_BOOL("isUnique",false,false)
			JSONRESP_STR("name",false,false)
			JSONRESP_SEC_GET(LayerIndex)
			JSONRESP_GETSTR("description",GetDescription)
			JSONRESP_GETSTR("fields",GetFields)
			JSONRESP_GETBOOL("isAscending",IsAscending)
			JSONRESP_GETBOOL("isUnique",IsUnique)
			JSONRESP_GETSTR("name",GetName)
			JSONRESP_END

			JSONRESP_BEGIN(FieldInfo)
			JSONRESP_STR("alias",false,false)
			JSONRESP_STR("defaultValue",false,true)
			JSONRESP_STR("domain",false,true)
			JSONRESP_BOOL("editable",false,false)
			JSONRESP_DOUBLE("length",false,false)
			JSONRESP_STR("modelName",false,false)
			JSONRESP_STR("name",false,false)
			JSONRESP_BOOL("nullable",false,false)
			JSONRESP_STR("type",false,false)
			JSONRESP_SEC_GET(FieldInfo)
			JSONRESP_GETSTR("alias",GetAlias)
			JSONRESP_GETSTROPT("defaultValue",GetDefaultValue)
			JSONRESP_GETSTROPT("domain",GetDomain)
			JSONRESP_GETBOOL("editable",IsEditable)
			JSONRESP_GETDOUBLE("length",GetLength,0.0)
			JSONRESP_GETSTR("modelName",GetModelName)
			JSONRESP_GETSTR("name",GetName)
			JSONRESP_GETBOOL("nullable",IsNullable)
			JSONRESP_GETSTR("type",GetType)
			JSONRESP_END

			JSONRESP_BEGIN(LayerInfo)
			JSONRESP_OBJ("advancedEditingCapabilities",false,false,AdvancedEditingCapabilities)
			JSONRESP_OBJ("advancedQueryCapabilities",false,false,AdvancedQueryCapabilities)
			JSONRESP_BOOL("allowGeometryUpdates",false,false)
			JSONRESP_BOOL("allowTrueCurvesUpdates",false,false)
			JSONRESP_OBJ("archivingInfo",false,false,ArchivingInfo)
			JSONRESP_BOOL("canScaleSymbols",false,false)
			JSONRESP_STR("capabilities",false,false)
			JSONRESP_STR("cimVersion",false,false)
			JSONRESP_STR("copyrightText",false,false)
			JSONRESP_DOUBLE("currentVersion",false,false)
			JSONRESP_OBJ("dateFieldsTimeReference",false,false,TimeReference)
			JSONRESP_BOOL("datesInUnknownTimezone",false,false)
			JSONRESP_BOOL("defaultVisibility",false,false)
			JSONRESP_STR("description",false,false)
			JSONRESP_STR("displayField",false,false)
			JSONRESP_OBJ("drawingInfo",false,false,DrawingInfo)
			JSONRESP_STR("editFieldsInfo",false,true)
			JSONRESP_OBJ("extent",false,false,Extent)
			JSONRESP_ARRAY_OBJ("fields",false,false,FieldInfo)
			JSONRESP_OBJ("geometryField",false,false,GeometryField)
			JSONRESP_STR("geometryType",false,false)
			JSONRESP_STR("globalIdField",false,false)
			JSONRESP_BOOL("hasAttachments",false,false)
			JSONRESP_BOOL("hasM",false,false)
			JSONRESP_BOOL("hasMetadata",false,false)
			JSONRESP_BOOL("hasZ",false,false)
			JSONRESP_STR("htmlPopupType",false,false)
			JSONRESP_DOUBLE("id",false,false)
			JSONRESP_ARRAY_OBJ("indexes",false,false,LayerIndex)
			JSONRESP_ARRAY_STR("infoInEstimates",false,false)
			JSONRESP_BOOL("isCoGoEnabled",false,false)
			JSONRESP_BOOL("isDataArchived",false,false)
			JSONRESP_BOOL("isDataBranchVersioned",false,false)
			JSONRESP_BOOL("isDataReplicaTracked",false,false)
			JSONRESP_BOOL("isDataVersioned",false,false)
			JSONRESP_DOUBLE("maxRecordCount",false,false)
			JSONRESP_DOUBLE("maxRecordCountFactor",false,false)
			JSONRESP_DOUBLE("maxScale",false,false)
			JSONRESP_DOUBLE("minScale",false,false)
			JSONRESP_STR("name",false,false)
			JSONRESP_STR("objectIdField",false,false)
			JSONRESP_BOOL("onlyAllowTrueCurveUpdatesByTrueCurveClients",false,false)
			JSONRESP_STR("ownershipBasedAccessControlForFeatures",false,true)
			JSONRESP_STR("parentLayer",false,true)
			JSONRESP_STR("preferredTimeReference",false,true)
			JSONRESP_ARRAY_OBJ("relationships",false,false,Relationship)
			JSONRESP_STR("serviceItemId",false,false)
			JSONRESP_OBJ("sourceSpatialReference",false,false,SpatialReference)
			JSONRESP_DOUBLE("standardMaxRecordCount",false,false)
			JSONRESP_DOUBLE("standardMaxRecordCountNoGeometry",false,false)
			JSONRESP_STR("subtypeField",false,false)
			JSONRESP_STR("supportedExportFormats",false,false)
			JSONRESP_STR("supportedQueryFormats",false,false)
			JSONRESP_ARRAY_STR("supportedSpatialRelationships",false,false)
			JSONRESP_BOOL("supportsASyncCalculate",false,false)
			JSONRESP_BOOL("supportsAdvancedQueries",false,false)
			JSONRESP_BOOL("supportsApplyEditsWithGlobalIds",false,false)
			JSONRESP_BOOL("supportsCalculate",false,false)
			JSONRESP_BOOL("supportsCoordinatesQuantization",false,false)
			JSONRESP_BOOL("supportsDatumTransformation",false,false)
			JSONRESP_BOOL("supportsExceedsLimitStatistics",false,false)
			JSONRESP_BOOL("supportsQuantizationEditMode",false,false)
			JSONRESP_BOOL("supportsRollbackOnFailureParameter",false,false)
			JSONRESP_BOOL("supportsStatistics",false,false)
			JSONRESP_BOOL("supportsValidateSQL",false,false)
			JSONRESP_BOOL("syncCanReturnChanges",false,false)
			JSONRESP_ARRAY_OBJ("templates",false,false,Template)
			JSONRESP_DOUBLE("tileMaxRecordCount",false,false)
			JSONRESP_STR("type",false,false)
			JSONRESP_STR("typeIdField",false,false)
			JSONRESP_ARRAY_OBJ("types",false,false,TypeInfo)
			JSONRESP_BOOL("useStandardizedQueries",false,false)
			JSONRESP_SEC_GET(LayerInfo)
			JSONRESP_GETOBJ("advancedEditingCapabilities",GetAdvancedEditingCapabilities,AdvancedEditingCapabilities)
			JSONRESP_GETOBJ("advancedQueryCapabilities",GetAdvancedQueryCapabilities,AdvancedQueryCapabilities)
			JSONRESP_GETBOOL("allowGeometryUpdates",AllowGeometryUpdates)
			JSONRESP_GETBOOL("allowTrueCurvesUpdates",AllowTrueCurvesUpdates)
			JSONRESP_GETOBJ("archivingInfo",GetArchivingInfo,ArchivingInfo)
			JSONRESP_GETBOOL("canScaleSymbols",CanScaleSymbols)
			JSONRESP_GETSTR("capabilities",GetCapabilities)
			JSONRESP_GETSTR("cimVersion",GetCimVersion)
			JSONRESP_GETSTR("copyrightText",GetCopyrightText)
			JSONRESP_GETDOUBLE("currentVersion",GetCurrentVersion,0.0)
			JSONRESP_GETOBJ("dateFieldsTimeReference",GetDateFieldsTimeReference,TimeReference)
			JSONRESP_GETBOOL("datesInUnknownTimezone",IsDatesInUnknownTimezone)
			JSONRESP_GETBOOL("defaultVisibility",IsDefaultVisibility)
			JSONRESP_GETSTR("description",GetDescription)
			JSONRESP_GETSTR("displayField",GetDisplayField)
			JSONRESP_GETOBJ("drawingInfo",GetDrawingInfo,DrawingInfo)
			JSONRESP_GETSTROPT("editFieldsInfo",GetEditFieldsInfo)
			JSONRESP_GETOBJ("extent",GetExtent,Extent)
			JSONRESP_GETARRAY_OBJ("fields",GetFields,FieldInfo)
			JSONRESP_GETOBJ("geometryField",GetGeometryField,GeometryField)
			JSONRESP_GETSTR("geometryType",GetGeometryType)
			JSONRESP_GETSTR("globalIdField",GetGlobalIdField)
			JSONRESP_GETBOOL("hasAttachments",HasAttachments)
			JSONRESP_GETBOOL("hasM",HasM)
			JSONRESP_GETBOOL("hasMetadata",HasMetadata)
			JSONRESP_GETBOOL("hasZ",HasZ)
			JSONRESP_GETSTR("htmlPopupType",GetHtmlPopupType)
			JSONRESP_GETDOUBLE("id",GetId,0.0)
			JSONRESP_GETARRAY_OBJ("indexes",GetIndexes,LayerIndex)
			JSONRESP_GETARRAY_STR("infoInEstimates",GetInfoInEstimates)
			JSONRESP_GETBOOL("isCoGoEnabled",IsCoGoEnabled)
			JSONRESP_GETBOOL("isDataArchived",IsDataArchived)
			JSONRESP_GETBOOL("isDataBranchVersioned",IsDataBranchVersioned)
			JSONRESP_GETBOOL("isDataReplicaTracked",IsDataReplicaTracked)
			JSONRESP_GETBOOL("isDataVersioned",IsDataVersioned)
			JSONRESP_GETDOUBLE("maxRecordCount",GetMaxRecordCount,0.0)
			JSONRESP_GETDOUBLE("maxRecordCountFactor",GetMaxRecordCountFactor,0.0)
			JSONRESP_GETDOUBLE("maxScale",GetMaxScale,0.0)
			JSONRESP_GETDOUBLE("minScale",GetMinScale,0.0)
			JSONRESP_GETSTR("name",GetName)
			JSONRESP_GETSTR("objectIdField",GetObjectIdField)
			JSONRESP_GETBOOL("onlyAllowTrueCurveUpdatesByTrueCurveClients",IsOnlyAllowTrueCurveUpdatesByTrueCurveClients)
			JSONRESP_GETSTROPT("ownershipBasedAccessControlForFeatures",GetOwnershipBasedAccessControlForFeatures)
			JSONRESP_GETSTROPT("parentLayer",GetParentLayer)
			JSONRESP_GETSTROPT("preferredTimeReference",GetPreferredTimeReference)
			JSONRESP_GETARRAY_OBJ("relationships",GetRelationships,Relationship)
			JSONRESP_GETSTR("serviceItemId",GetServiceItemId)
			JSONRESP_GETOBJ("sourceSpatialReference",GetSourceSpatialReference,SpatialReference)
			JSONRESP_GETDOUBLE("standardMaxRecordCount",GetStandardMaxRecordCount,0.0)
			JSONRESP_GETDOUBLE("standardMaxRecordCountNoGeometry",GetStandardMaxRecordCountNoGeometry,0.0)
			JSONRESP_GETSTR("subtypeField",GetSubtypeField)
			JSONRESP_GETSTR("supportedExportFormats",GetSupportedExportFormats)
			JSONRESP_GETSTR("supportedQueryFormats",GetSupportedQueryFormats)
			JSONRESP_GETARRAY_STR("supportedSpatialRelationships",GetSupportedSpatialRelationships)
			JSONRESP_GETBOOL("supportsASyncCalculate",IsSupportsASyncCalculate)
			JSONRESP_GETBOOL("supportsAdvancedQueries",IsSupportsAdvancedQueries)
			JSONRESP_GETBOOL("supportsApplyEditsWithGlobalIds",IsSupportsApplyEditsWithGlobalIds)
			JSONRESP_GETBOOL("supportsCalculate",IsSupportsCalculate)
			JSONRESP_GETBOOL("supportsCoordinatesQuantization",IsSupportsCoordinatesQuantization)
			JSONRESP_GETBOOL("supportsDatumTransformation",IsSupportsDatumTransformation)
			JSONRESP_GETBOOL("supportsExceedsLimitStatistics",IsSupportsExceedsLimitStatistics)
			JSONRESP_GETBOOL("supportsQuantizationEditMode",IsSupportsQuantizationEditMode)
			JSONRESP_GETBOOL("supportsRollbackOnFailureParameter",IsSupportsRollbackOnFailureParameter)
			JSONRESP_GETBOOL("supportsStatistics",IsSupportsStatistics)
			JSONRESP_GETBOOL("supportsValidateSQL",IsSupportsValidateSQL)
			JSONRESP_GETBOOL("syncCanReturnChanges",IsSyncCanReturnChanges)
			JSONRESP_GETARRAY_OBJ("templates",GetTemplates,Template)
			JSONRESP_GETDOUBLE("tileMaxRecordCount",GetTileMaxRecordCount,0.0)
			JSONRESP_GETSTR("type",GetType)
			JSONRESP_GETSTR("typeIdField",GetTypeIdField)
			JSONRESP_GETARRAY_OBJ("types",GetTypes,TypeInfo)
			JSONRESP_GETBOOL("useStandardizedQueries",UseStandardizedQueries)
			JSONRESP_END

		private:
			NotNullPtr<Text::String> url;
			NotNullPtr<Text::String> name;
			NotNullPtr<Net::SocketFactory> sockf;
			Optional<Net::SSLEngine> ssl;

		public:
			ESRIFeatureServer(Text::CStringNN url, NotNullPtr<Net::SocketFactory> sockf, Optional<Net::SSLEngine> ssl);
			virtual ~ESRIFeatureServer();

			Optional<LayerInfo> GetLayerInfo();

			NotNullPtr<Text::String> GetURL() const;
			NotNullPtr<Text::String> GetName() const;
		};
	}
}
#endif
